# Generated by Django 5.1.1 on 2025-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_location_options_alter_post_options_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                upload_to="blog_images/", verbose_name="изображение"
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
