# Generated by Django 5.1.1 on 2025-04-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="blog_images/", verbose_name="изображение"
            ),
        ),
    ]
